name: firebase_auth_mvvm
description: Firebase Auth (Email/Google) with MVVM, Repository, Provider, get_it, Firestore profile.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State & DI
  provider: ^6.1.5
  get_it: ^8.2.0

  # Firebase (compatible with Flutter 3.35 / Dart 3.9)
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  google_sign_in: ^7.2.0

  # Lints
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
