// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmFGrFUhPoX2qIVju4YTnWdb_i4R7Nx8',
    appId: '1:385248547963:web:45a581c0d41c46c3ba7ede',
    messagingSenderId: '385248547963',
    projectId: 'auth-mvvm-facetunebeauty',
    authDomain: 'auth-mvvm-facetunebeauty.firebaseapp.com',
    storageBucket: 'auth-mvvm-facetunebeauty.firebasestorage.app',
    measurementId: 'G-64CNR69LBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn2UBadnT8DJYTzB5nJxIVtYNCRu-Wbm0',
    appId: '1:535719209505:android:12f416c6af0fc3e6441160',
    messagingSenderId: '535719209505',
    projectId: 'appdev-b107f',
    storageBucket: 'appdev-b107f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-DSDD8k0U3U65yIz3FillLUJULcai4nk',
    appId: '1:535719209505:ios:23584749cbec70da441160',
    messagingSenderId: '535719209505',
    projectId: 'appdev-b107f',
    storageBucket: 'appdev-b107f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthMvvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-DSDD8k0U3U65yIz3FillLUJULcai4nk',
    appId: '1:535719209505:ios:23584749cbec70da441160',
    messagingSenderId: '535719209505',
    projectId: 'appdev-b107f',
    storageBucket: 'appdev-b107f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthMvvm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfnHIo8175yWAelTYxtZCKuvVd1oTGB38',
    appId: '1:535719209505:web:38089eb13d2f5250441160',
    messagingSenderId: '535719209505',
    projectId: 'appdev-b107f',
    authDomain: 'appdev-b107f.firebaseapp.com',
    storageBucket: 'appdev-b107f.firebasestorage.app',
    measurementId: 'G-H7XT33B2YS',
  );
}